### ISSUE TITLE
zss and zrr files not output when requested

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mt_metadata#94] opened 2022-08-28 18:03 UTC
Currently .zss, .zrr are not supported in mt_metadata.

in the code below, tf_cls is a populated object of type `mt_metadata.transfer_functions.core.TF`

Executing:
`tf_cls.write_tf_file("testzss.zss", file_type="zss")`
or
`tf_cls.write_tf_file("testzss.zss", file_type="zmm")`
yields:
`KeyError: "Writer for the file type zss does not currently exist. Current writers ['edi', 'zmm', 'j', 'emtfxml', 'avg']"`

See aurora issue 139 [https://github.com/simpeg/aurora/issues/139](url)

**Comment by kujaku11** [comment] 2022-08-30 18:04
Duplicate of #84

**Closed by kujaku11** 2022-08-30 18:04 UTC
Labels: bug
